# Generated by Django 4.0.6 on 2022-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture_time_slot',
            fields=[
                ('slot_id_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('slot_time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_time_table',
            fields=[
                ('Lec_tt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Faculty_id', models.IntegerField()),
                ('Subject_code', models.PositiveSmallIntegerField()),
                ('Semester', models.PositiveSmallIntegerField()),
                ('Division', models.CharField(max_length=255)),
                ('Day', models.CharField(max_length=255)),
                ('slot_id_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student_attendance_report',
            fields=[
                ('Enrollment_no', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Lec_tt_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
