# Generated by Django 4.0.6 on 2022-10-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postattendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendance_report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_attendance_report',
            name='Enrollment_no',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='student_attendance_report',
            unique_together={('Enrollment_no', 'Lec_tt_id', 'date')},
        ),
    ]
